# 머신러닝의 개념과 용어

## Limit Of Explicit Programming
명시적 프로그래밍을 통한 문제 해결의 한계 - Ex) 스팸메일 필터링, 자율주행

## What is ML
해결해야할 문제의 원인과 결과를 데이터로 입력해 그 상관관계를 학습을 통해 파악하는 것

## Supervised Learning
많은 레이블 데이터를 이용해 학습

## Unsupervised Learning
레이블 데이터 없이, 데이터를 그룹화, 클러스터링하여 학습

## What is regression
목적값이 continuous 한 연속성을 가지고 있을 때

## What is classification
목적값이 이산적일 때

## Linear Regression
입력과 출력의 상관관계가 선형적일 것으로 예측하는 방식

## Multinomial Classification
$$
\begin{bmatrix} 
W_1 & W_2 & W_3
\end{bmatrix}
\begin{bmatrix} 
x_1 \\ x_2 \\ x_3
\end{bmatrix} = 
\begin{bmatrix} 
W_1x_1 + W_2x_2 + W_3x_3
\end{bmatrix}
$$

$$
\begin{bmatrix} 
W_{a1} & W_{a2} & W_{a3} \\
W_{b1} & W_{b2} & W_{b3} \\
W_{c1} & W_{c2} & W_{c3} \\
\end{bmatrix}
\begin{bmatrix} 
x1 \\ x2 \\ x3
\end{bmatrix} = 
\begin{bmatrix} 
W_{a1}x_1 + W_{a2}x_2 + W_{a3}x_3 \\
W_{b1}x_1 + W_{b2}x_2 + W_{b3}x_3 \\
W_{c1}x_1 + W_{c2}x_2 + W_{c3}x_3 \\
\end{bmatrix} = 
\begin{bmatrix} 
\bar{y_{a}} \\
\bar{y_{b}} \\
\bar{y_{c}}
\end{bmatrix}
$$

# Tensorflow

## Version

In [ ]:
import tensorflow as tf
tf.__version__

## Hello Tensorflow

In [ ]:
# Create a constant op
# This op is added as a node to the default graph
hello = tf.constant("Hello, Tensorflow!")

# start a TF session
sess = tf.Session()

# run the op and get result
print(sess.run(hello))

## Tensors

In [ ]:
[1., 2., 3.]
[[1., 2., 3.], [4., 5., 6.]]
[[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]]

## Computational Graph

In [ ]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0) # also tf.float32 implicitly
node3 = tf.add(node1, node2)

In [ ]:
print("node1:", node1, "node2:", node2)
print("node3: ", node3)

In [ ]:
sess = tf.Session()
print("sess.run(node1, node2): ", sess.run([node1, node2]))
print("sess.run(node3): ", sess.run(node3))

![Graph](https://www.tensorflow.org/images/getting_started_adder.png)

In [ ]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b  # + provides a shortcut for tf.add(a, b)

print(sess.run(adder_node, feed_dict={a: 3, b: 4.5}))
print(sess.run(adder_node, feed_dict={a: [1,3], b: [2, 4]}))

In [ ]:
add_and_triple = adder_node * 3.
print(sess.run(add_and_triple, feed_dict={a: 3, b:4.5}))

In [ ]:
x_train = [1, 2, 3,]
y_train = [1, 2, 3,]

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Out hypothesis Wx + b
hypo = W * x_train + b

# Cost(Loss) Function
cost = tf.reduce_mean(tf.square(hypo - y_train))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.005)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

# Fit the Line
for step in range(20001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W), sess.run(b))

In [ ]:
# Placeholders

x_placeholder = tf.placeholder(tf.float32)
y_placeholder = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Out hypothesis Wx + b
hypo = W * x_placeholder + b

# Cost(Loss) Function
cost = tf.reduce_mean(tf.square(hypo - y_placeholder))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.005)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(20001):
    cost_val, W_val, b_val, _ = \
    sess.run([cost, W, b,  b], feed_dict={x_placeholder: [1, 2, 3], y_placeholder: [1, 2, 3]})
    
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)

In [ ]:
import matplotlib.pyplot as plt

X = [1, 2, 3,]
Y = [1, 2, 3,]

W = tf.placeholder(tf.float32)

# Out hypothesis Wx + b
hypo = W * X

# Cost(Loss) Function
cost = tf.reduce_mean(tf.square(hypo - Y))

# Launch the graph in a session
sess = tf.Session()

# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

W_val = []
cost_val = []

for i in range(-30, 50):
    feed_W = i * 0.1
    curr_cost, curr_W = sess.run([cost, W], feed_dict={W: feed_W})
    W_val.append(curr_W)
    cost_val.append(curr_cost)
        
# Show the cost function
plt.plot(W_val, cost_val)
plt.show()

In [ ]:
x_data = [1, 2, 3,]
y_data = [1, 2, 3,]

W = tf.Variable(tf.random_normal([1]), name='weight')
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Out hypothesis Wx + b
hypo = W * X

# Cost(Loss) Function
cost = tf.reduce_sum(tf.square(hypo - Y))

learning_rate = 0.1
gradient = tf.reduce_mean((W * X - Y) * X)
descent = W - learning_rate * gradient
update = W.assign(descent)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(21):
    sess.run(update, feed_dict={X: x_data, Y:y_data})
    print(step, sess.run(cost, feed_dict={X: x_data, Y:y_data}), sess.run(W))

In [3]:
import tensorflow as tf

X = [1, 2, 3,]
Y = [1, 2, 3,]

W = tf.Variable(-3.0)

# Out hypothesis Wx + b
hypo = W * X

# Cost(Loss) Function
cost = tf.reduce_mean(tf.square(hypo - Y))

# Minimize: Gradient Descent Magic
learning_rate = 0.1
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(100):
    print(step, sess.run(W))
    sess.run(train)

0 -3.0
1 0.733333
2 0.982222
3 0.998815
4 0.999921
5 0.999995
6 1.0
7 1.0
8 1.0
9 1.0
10 1.0
11 1.0
12 1.0
13 1.0
14 1.0
15 1.0
16 1.0
17 1.0
18 1.0
19 1.0
20 1.0
21 1.0
22 1.0
23 1.0
24 1.0
25 1.0
26 1.0
27 1.0
28 1.0
29 1.0
30 1.0
31 1.0
32 1.0
33 1.0
34 1.0
35 1.0
36 1.0
37 1.0
38 1.0
39 1.0
40 1.0
41 1.0
42 1.0
43 1.0
44 1.0
45 1.0
46 1.0
47 1.0
48 1.0
49 1.0
50 1.0
51 1.0
52 1.0
53 1.0
54 1.0
55 1.0
56 1.0
57 1.0
58 1.0
59 1.0
60 1.0
61 1.0
62 1.0
63 1.0
64 1.0
65 1.0
66 1.0
67 1.0
68 1.0
69 1.0
70 1.0
71 1.0
72 1.0
73 1.0
74 1.0
75 1.0
76 1.0
77 1.0
78 1.0
79 1.0
80 1.0
81 1.0
82 1.0
83 1.0
84 1.0
85 1.0
86 1.0
87 1.0
88 1.0
89 1.0
90 1.0
91 1.0
92 1.0
93 1.0
94 1.0
95 1.0
96 1.0
97 1.0
98 1.0
99 1.0


In [4]:
import tensorflow as tf

X = [1, 2, 3,]
Y = [1, 2, 3,]

W = tf.Variable(5.0)

# Out hypothesis Wx + b
hypo = W * X

# Mangual gradient
gradient = tf.reduce_mean((W * X - Y) * X) * 2

# Cost(Loss) Function
cost = tf.reduce_mean(tf.square(hypo - Y))

# Minimize: Gradient Descent Magic
learning_rate = 0.01
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)

# Get gradientts
gvs = optimizer.compute_gradients(cost, [W])

# Apply Gradients
apply_gradients = optimizer.apply_gradients(gvs)

# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(100):
    print(step, sess.run([gradient, W, gvs]))
    sess.run(apply_gradients)

0 [37.333332, 5.0, [(37.333332, 5.0)]]
1 [33.848888, 4.6266665, [(33.848888, 4.6266665)]]
2 [30.689655, 4.2881775, [(30.689655, 4.2881775)]]
3 [27.825289, 3.981281, [(27.825289, 3.981281)]]
4 [25.228264, 3.7030282, [(25.228264, 3.7030282)]]
5 [22.873627, 3.4507456, [(22.873627, 3.4507456)]]
6 [20.738754, 3.2220094, [(20.738754, 3.2220094)]]
7 [18.803141, 3.014622, [(18.803141, 3.014622)]]
8 [17.04818, 2.8265905, [(17.048178, 2.8265905)]]
9 [15.457016, 2.6561089, [(15.457016, 2.6561089)]]
10 [14.014363, 2.5015388, [(14.014362, 2.5015388)]]
11 [12.706355, 2.3613951, [(12.706355, 2.3613951)]]
12 [11.520428, 2.2343316, [(11.520428, 2.2343316)]]
13 [10.445188, 2.1191273, [(10.445188, 2.1191273)]]
14 [9.4703045, 2.0146754, [(9.4703045, 2.0146754)]]
15 [8.5864086, 1.9199723, [(8.5864077, 1.9199723)]]
16 [7.7850103, 1.8341082, [(7.7850103, 1.8341082)]]
17 [7.0584097, 1.7562581, [(7.0584097, 1.7562581)]]
18 [6.3996248, 1.6856741, [(6.3996248, 1.6856741)]]
19 [5.8023272, 1.6216779, [(5.8023272, 

In [6]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')

b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * bw3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001):
   cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                        feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
   if step % 10 == 0:
       print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)



0 Cost:  77754.1 
Prediction:
 [ -83.99380493 -120.67478943 -108.35884857 -120.61877441  -95.15387726]
10 Cost:  67.0902 
Prediction:
 [ 162.53874207  175.69882202  183.63197327  197.35554504  130.91644287]
20 Cost:  66.0215 
Prediction:
 [ 163.25308228  176.61715698  184.50575256  198.3106842   131.62876892]
30 Cost:  65.666 
Prediction:
 [ 163.2237854   176.64152527  184.49876404  198.3066864   131.65916443]
40 Cost:  65.3124 
Prediction:
 [ 163.19230652  176.6631012   184.48908997  198.29977417  131.68740845]
50 Cost:  64.9608 
Prediction:
 [ 163.16090393  176.68460083  184.47946167  198.2928772   131.71556091]
60 Cost:  64.6111 
Prediction:
 [ 163.12962341  176.70608521  184.46987915  198.286026    131.74368286]
70 Cost:  64.2632 
Prediction:
 [ 163.09840393  176.72747803  184.46029663  198.2791748   131.77171326]
80 Cost:  63.9172 
Prediction:
 [ 163.06723022  176.74879456  184.45071411  198.27230835  131.79962158]
90 Cost:  63.5731 
Prediction:
 [ 163.03619385  176.77011108  184.

820 Cost:  42.8825 
Prediction:
 [ 160.98171997  178.177948    183.81095886  197.81517029  133.6703949 ]
830 Cost:  42.6521 
Prediction:
 [ 160.95631409  178.19535828  183.80316162  197.80960083  133.69319153]
840 Cost:  42.4229 
Prediction:
 [ 160.93095398  178.21273804  183.7953949   197.80406189  133.71592712]
850 Cost:  42.195 
Prediction:
 [ 160.90567017  178.23005676  183.78762817  197.79850769  133.73858643]
860 Cost:  41.9683 
Prediction:
 [ 160.88044739  178.24731445  183.77989197  197.79299927  133.76119995]
870 Cost:  41.7427 
Prediction:
 [ 160.85531616  178.26457214  183.77217102  197.78749084  133.78375244]
880 Cost:  41.5185 
Prediction:
 [ 160.83024597  178.28175354  183.76448059  197.78201294  133.80625916]
890 Cost:  41.2954 
Prediction:
 [ 160.80522156  178.29890442  183.75682068  197.77653503  133.82867432]
900 Cost:  41.0736 
Prediction:
 [ 160.78027344  178.315979    183.74914551  197.77105713  133.85102844]
910 Cost:  40.853 
Prediction:
 [ 160.75541687  178.3330

1680 Cost:  26.9998 
Prediction:
 [ 159.0287323   179.51615906  183.21168518  197.38815308  135.42111206]
1690 Cost:  26.8552 
Prediction:
 [ 159.00857544  179.529953    183.20549011  197.38374329  135.43916321]
1700 Cost:  26.7114 
Prediction:
 [ 158.98847961  179.54371643  183.1993103   197.37937927  135.45715332]
1710 Cost:  26.5684 
Prediction:
 [ 158.96846008  179.5574646   183.19317627  197.375       135.47509766]
1720 Cost:  26.4261 
Prediction:
 [ 158.94847107  179.57113647  183.18702698  197.37063599  135.49301147]
1730 Cost:  26.2847 
Prediction:
 [ 158.92854309  179.58479309  183.18092346  197.36628723  135.510849  ]
1740 Cost:  26.144 
Prediction:
 [ 158.90867615  179.59838867  183.17483521  197.36193848  135.52865601]
1750 Cost:  26.004 
Prediction:
 [ 158.88885498  179.61199951  183.16876221  197.35765076  135.54641724]
1760 Cost:  25.8648 
Prediction:
 [ 158.86911011  179.62553406  183.16267395  197.35333252  135.56413269]
1770 Cost:  25.7264 
Prediction:
 [ 158.84938049

In [7]:
import tensorflow as tf
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
   cost_val, hy_val, _ = sess.run(
       [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
   if step % 10 == 0:
       print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)



0 Cost:  79700.5 
Prediction:
 [[ -99.71774292]
 [-116.21123505]
 [-116.66260529]
 [-124.56324768]
 [ -89.6095047 ]]
10 Cost:  3.03952 
Prediction:
 [[ 150.0161438 ]
 [ 183.95222473]
 [ 179.09263611]
 [ 197.50617981]
 [ 139.34063721]]
20 Cost:  2.30831 
Prediction:
 [[ 150.77075195]
 [ 184.8611908 ]
 [ 179.98725891]
 [ 198.47982788]
 [ 140.03492737]]
30 Cost:  2.30668 
Prediction:
 [[ 150.77203369]
 [ 184.86470032]
 [ 179.98974609]
 [ 198.48193359]
 [ 140.03860474]]
40 Cost:  2.30506 
Prediction:
 [[ 150.77104187]
 [ 184.86546326]
 [ 179.98954773]
 [ 198.48109436]
 [ 140.04017639]]
50 Cost:  2.30346 
Prediction:
 [[ 150.77003479]
 [ 184.86621094]
 [ 179.98931885]
 [ 198.48025513]
 [ 140.04173279]]
60 Cost:  2.30187 
Prediction:
 [[ 150.76902771]
 [ 184.86695862]
 [ 179.98908997]
 [ 198.47941589]
 [ 140.04328918]]
70 Cost:  2.30023 
Prediction:
 [[ 150.76805115]
 [ 184.8677063 ]
 [ 179.98887634]
 [ 198.4785614 ]
 [ 140.04486084]]
80 Cost:  2.29865 
Prediction:
 [[ 150.76705933]
 [ 184.8

860 Cost:  2.18434 
Prediction:
 [[ 150.69989014]
 [ 184.91986084]
 [ 179.97488403]
 [ 198.41508484]
 [ 140.15834045]]
870 Cost:  2.18299 
Prediction:
 [[ 150.6991272 ]
 [ 184.92044067]
 [ 179.97473145]
 [ 198.41430664]
 [ 140.15966797]]
880 Cost:  2.18163 
Prediction:
 [[ 150.69839478]
 [ 184.92100525]
 [ 179.97459412]
 [ 198.41352844]
 [ 140.16098022]]
890 Cost:  2.18029 
Prediction:
 [[ 150.69764709]
 [ 184.92156982]
 [ 179.97444153]
 [ 198.41275024]
 [ 140.16229248]]
900 Cost:  2.17896 
Prediction:
 [[ 150.69691467]
 [ 184.92214966]
 [ 179.9743042 ]
 [ 198.4119873 ]
 [ 140.16360474]]
910 Cost:  2.17762 
Prediction:
 [[ 150.69619751]
 [ 184.92274475]
 [ 179.97418213]
 [ 198.41123962]
 [ 140.16493225]]
920 Cost:  2.17627 
Prediction:
 [[ 150.69546509]
 [ 184.92329407]
 [ 179.9740448 ]
 [ 198.41046143]
 [ 140.16624451]]
930 Cost:  2.17495 
Prediction:
 [[ 150.69473267]
 [ 184.92385864]
 [ 179.97390747]
 [ 198.40968323]
 [ 140.16752625]]
940 Cost:  2.17362 
Prediction:
 [[ 150.69400024

1670 Cost:  2.08256 
Prediction:
 [[ 150.64801025]
 [ 184.96086121]
 [ 179.96589661]
 [ 198.35493469]
 [ 140.25744629]]
1680 Cost:  2.08138 
Prediction:
 [[ 150.64744568]
 [ 184.96130371]
 [ 179.96580505]
 [ 198.35420227]
 [ 140.25857544]]
1690 Cost:  2.08021 
Prediction:
 [[ 150.64691162]
 [ 184.96174622]
 [ 179.9657135 ]
 [ 198.35348511]
 [ 140.25968933]]
1700 Cost:  2.07904 
Prediction:
 [[ 150.64637756]
 [ 184.96217346]
 [ 179.96562195]
 [ 198.35276794]
 [ 140.26081848]]
1710 Cost:  2.07789 
Prediction:
 [[ 150.64582825]
 [ 184.96260071]
 [ 179.96556091]
 [ 198.35206604]
 [ 140.26193237]]
1720 Cost:  2.07673 
Prediction:
 [[ 150.64529419]
 [ 184.96302795]
 [ 179.96546936]
 [ 198.35134888]
 [ 140.26304626]]
1730 Cost:  2.07555 
Prediction:
 [[ 150.64476013]
 [ 184.9634552 ]
 [ 179.96539307]
 [ 198.35063171]
 [ 140.26417542]]
1740 Cost:  2.0744 
Prediction:
 [[ 150.64424133]
 [ 184.96388245]
 [ 179.96531677]
 [ 198.34992981]
 [ 140.26528931]]
1750 Cost:  2.07324 
Prediction:
 [[ 150.

In [1]:
# Loading Data From File
 
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]
